<?xml version="1.0" encoding="utf-8" ?>

<Experiment>
<RexHeader>REX 3.15</RexHeader>
<Notes>I491 LDNA assay</Notes>
<Operator>SD</Operator>
<Rotor>2</Rotor>
<RunId></RunId>
<StartTime></StartTime>
<FinishTime></FinishTime>
<TemplateFilename>C:\Program Files (x86)\Rotor-Gene Q Software\Templates\normal.ret</TemplateFilename>
<HighSpeedRotor>True</HighSpeedRotor>
<SpikeSuppression>True</SpikeSuppression>
<ReactionVolume>20</ReactionVolume>
<OilLayerVolume>0</OilLayerVolume>
<AmbientCompensation>True</AmbientCompensation>
<Signature>2f76ba6d28aa11b80772d6ab4c74f1ab</Signature>
<TemplateSignatureState>0</TemplateSignatureState>
<Samples>
<TranslatedRows>False</TranslatedRows>
<Format></Format>
<ConcentrationUnit>Copies</ConcentrationUnit>
<IDFormat>1</IDFormat>
<SyncPages>False</SyncPages>
<ReadOnly>False</ReadOnly>
<Page>
<Name>Page 1</Name>
<Suitabilities>
<SuitableForAll>True</SuitableForAll>
</Suitabilities>
<Sample>
<ID>1</ID>
<Name>NTC</Name>
<Type>3</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>8421504</Color>
<TubePosition>1</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>2</ID>
<Name>WT I491 MEP491-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>4227072</Color>
<TubePosition>2</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>3</ID>
<Name>I491F MEP492-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>255</Color>
<TubePosition>3</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>4</ID>
<Name>I491N MEP493</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711680</Color>
<TubePosition>4</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>5</ID>
<Name>I491M MEP494</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711808</Color>
<TubePosition>5</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>6</ID>
<Name>NTC</Name>
<Type>3</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>8355711</Color>
<TubePosition>6</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>7</ID>
<Name>WT I491 MEP491-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>4227072</Color>
<TubePosition>7</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>8</ID>
<Name>I491F MEP492-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>255</Color>
<TubePosition>8</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>9</ID>
<Name>I491N MEP493</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711680</Color>
<TubePosition>9</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>10</ID>
<Name>I491M MEP494</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711808</Color>
<TubePosition>10</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>11</ID>
<Name>NTC</Name>
<Type>3</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>8355711</Color>
<TubePosition>11</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>12</ID>
<Name>WT I491 MEP491-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>4227072</Color>
<TubePosition>12</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>13</ID>
<Name>I491F MEP492-2</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>255</Color>
<TubePosition>13</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>14</ID>
<Name>I491N MEP493</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711680</Color>
<TubePosition>14</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>15</ID>
<Name>I491M MEP494</Name>
<Type>2</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16711808</Color>
<TubePosition>15</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>16</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>True</Selected>
<Color>16777215</Color>
<TubePosition>16</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>17</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>17</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>18</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>18</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>19</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>19</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>20</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>20</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>21</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>21</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>22</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>22</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>23</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>23</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>24</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>24</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>25</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>25</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>26</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>26</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>27</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>27</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>28</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>28</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>29</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>29</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>30</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>30</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>31</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>31</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>32</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>32</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>33</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>33</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>34</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>34</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>35</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>35</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
<Sample>
<ID>36</ID>
<Name></Name>
<Type>0</Type>
<GivenConc>0</GivenConc>
<Selected>False</Selected>
<Color>16777215</Color>
<TubePosition>36</TubePosition>
<LinePattern>0</LinePattern>
<ReadOnly>False</ReadOnly>
</Sample>
</Page>
<Groups></Groups>
<CustomColumns></CustomColumns>
<HiddenColumns></HiddenColumns>
</Samples>
<ChannelTypes>
<ChannelType>
<Name>Green</Name>
<Gain>5</Gain>
<Detector>1</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[Green][1][1]</Key>
</ChannelType>
<ChannelType>
<Name>Yellow</Name>
<Gain>5</Gain>
<Detector>2</Detector>
<Source>2</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[Yellow][2][2]</Key>
</ChannelType>
<ChannelType>
<Name>Orange</Name>
<Gain>5</Gain>
<Detector>3</Detector>
<Source>3</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[Orange][3][3]</Key>
</ChannelType>
<ChannelType>
<Name>Red</Name>
<Gain>5</Gain>
<Detector>7</Detector>
<Source>4</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[Red][4][7]</Key>
</ChannelType>
<ChannelType>
<Name>Crimson</Name>
<Gain>7</Gain>
<Detector>8</Detector>
<Source>5</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[Crimson][5][8]</Key>
</ChannelType>
<ChannelType>
<Name>HRM</Name>
<Gain>7</Gain>
<Detector>1</Detector>
<Source>7</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[HRM][7][1]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em orange 5</Name>
<Gain>5</Gain>
<Detector>3</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em orange 5][1][3]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em orange 7</Name>
<Gain>7</Gain>
<Detector>3</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em orange 7][1][3]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em green 5</Name>
<Gain>5</Gain>
<Detector>1</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em green 5][1][1]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em green 7</Name>
<Gain>7</Gain>
<Detector>1</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em green 7][1][1]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em green 9</Name>
<Gain>9</Gain>
<Detector>1</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em green 9][1][1]</Key>
</ChannelType>
<ChannelType>
<Name>ex green em orange 9</Name>
<Gain>9</Gain>
<Detector>3</Detector>
<Source>1</Source>
<Hidden>False</Hidden>
<Type>3</Type>
<Key>[ex green em orange 9][1][3]</Key>
</ChannelType>
</ChannelTypes>
<Record>
<Field>
<Name>Run Wizard</Name>
<Value>Advanced</Value>
<Type>3</Type>
<Group>General</Group>
<ExpandParent>True</ExpandParent>
</Field>
<Field>
<Name></Name>
<Value>Saved At 11/19/2024 3:19:37 PM By Unauthenticated Domain/Unknown User</Value>
<Type>3</Type>
<Group>Security Audit Trail Summary</Group>
<ExpandParent>True</ExpandParent>
</Field>
<Field>
<Name></Name>
<Value>Saved At 11/19/2024 3:19:37 PM By Unauthenticated Domain/Unknown User (Authentication Disabled)</Value>
<Type>3</Type>
<Group>Security Audit Trail Detail</Group>
<ExpandParent>False</ExpandParent>
</Field>
</Record>
<RawChannels></RawChannels>
<Profile>
<SharedData>
<CalibrateBefore>0</CalibrateBefore>
<OptoDenatCalibrator>
<TubePosition>1</TubePosition>
<StartTemp>80</StartTemp>
<EndTemp>95</EndTemp>
<HoldFor>180</HoldFor>
<TempOffset>0</TempOffset>
</OptoDenatCalibrator>
</SharedData>
<HoldCycle>
<IsDenature>False</IsDenature>
<Temperature>95</Temperature>
<HoldFor>120</HoldFor>
<RotorSpeed>1</RotorSpeed>
</HoldCycle>
<Cycle>
<RepeatCount>40</RepeatCount>
<NormalCyclePoint>
<Temperature>95</Temperature>
<RemainFor>5</RemainFor>
<AcquirePeriod>0</AcquirePeriod>
<RotorSpeed>1</RotorSpeed>
<TouchdownDegrees>0</TouchdownDegrees>
<TouchdownCycles>0</TouchdownCycles>
<LongRangeTime>0</LongRangeTime>
<LongRangeCycles>0</LongRangeCycles>
</NormalCyclePoint>
<NormalCyclePoint>
<Temperature>57</Temperature>
<RemainFor>20</RemainFor>
<AcquirePeriod>0</AcquirePeriod>
<RotorSpeed>1</RotorSpeed>
<TouchdownDegrees>0</TouchdownDegrees>
<TouchdownCycles>0</TouchdownCycles>
<LongRangeTime>0</LongRangeTime>
<LongRangeCycles>0</LongRangeCycles>
<AcquireTo>
<ID>97525200</ID>
<ChannelTypeRef>[ex green em green 5][1][1]</ChannelTypeRef>
<ChannelTypeRef>[ex green em green 7][1][1]</ChannelTypeRef>
<ChannelTypeRef>[ex green em green 9][1][1]</ChannelTypeRef>
</AcquireTo>
</NormalCyclePoint>
</Cycle>
<MeltCycle>
<StartTemp>95</StartTemp>
<EndTemp>50</EndTemp>
<HoldFor>1</HoldFor>
<TempStep>-.1</TempStep>
<RotorSpeed>1</RotorSpeed>
<KeepLEDOn>False</KeepLEDOn>
<AutoGainBefore>False</AutoGainBefore>
<AutoGainUpperLimit>95</AutoGainUpperLimit>
</MeltCycle>
<MeltCycle>
<StartTemp>65</StartTemp>
<EndTemp>95</EndTemp>
<HoldFor>5</HoldFor>
<TempStep>1</TempStep>
<RotorSpeed>1</RotorSpeed>
<KeepLEDOn>False</KeepLEDOn>
<AutoGainBefore>False</AutoGainBefore>
<AutoGainUpperLimit>95</AutoGainUpperLimit>
<AcquireTo>
<ID>97526224</ID>
<ChannelTypeRef>[ex green em green 5][1][1]</ChannelTypeRef>
<ChannelTypeRef>[ex green em green 7][1][1]</ChannelTypeRef>
<ChannelTypeRef>[ex green em green 9][1][1]</ChannelTypeRef>
<ChannelTypeRef>[ex green em orange 5][1][3]</ChannelTypeRef>
<ChannelTypeRef>[ex green em orange 7][1][3]</ChannelTypeRef>
<ChannelTypeRef>[ex green em orange 9][1][3]</ChannelTypeRef>
</AcquireTo>
</MeltCycle>
</Profile>
<Traces>
<Tmp2>30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54 30.54</Tmp2>
<Tmp4>29 28.9 29 29 29 28.9 29 29 28.9 29 28.9 29 28.9 29 29 28.9 29 29 28.9 29 29 28.9 29 29 29 28.9 28.8 28.9 29 29 29 29 29 29 29 28.8 29 29 29 29 29</Tmp4>
<TmpSample>30.7366108686964 30.7166841622158 30.6987770471942 30.6663517427454 30.6533234475147 30.6417382114954 30.6314359067528 30.6221607315768 30.613689029928 30.6062205736827 30.5994507392638 30.5931640997713 30.5876822791613 30.5826442802599 30.5782809345447 30.5743674138085 30.5706429604327 30.5675102819206 30.5646978621081 30.562175134366 30.5599257089149 30.557871142727 30.5560284255749 30.5543898141721 30.5529313922383 30.5515980192894 30.550402132188 30.5493295545865 30.5483922186124 30.5475342687752 30.5467640285124 30.5460844497399 30.5454570740836 30.5448991887331 30.5443940269061 30.5439370911969 30.5435276723206 30.5431732487369 30.5428488424788 30.5425653857121 30.5423028964712</TmpSample>
</Traces>
<AutoGain>
<Temperature>60</Temperature>
<Mode>1</Mode>
</AutoGain>
<DefaultAllelicGenotypes>
<Genotypes>
<Genotype>
<Name>Wild Type</Name>
<ShortName></ShortName>
<BinBits>1</BinBits>
</Genotype>
<Genotype>
<Name>Heterozygous</Name>
<ShortName></ShortName>
<BinBits>3</BinBits>
</Genotype>
<Genotype>
<Name>Mutant</Name>
<ShortName></ShortName>
<BinBits>2</BinBits>
</Genotype>
</Genotypes>
</DefaultAllelicGenotypes>
<DefaultScatterGenotypes>
<Genotypes>
<Genotype>
<Name>Wild Type</Name>
<ShortName></ShortName>
<BinBits>1</BinBits>
</Genotype>
<Genotype>
<Name>Heterozygous</Name>
<ShortName></ShortName>
<BinBits>3</BinBits>
</Genotype>
<Genotype>
<Name>None</Name>
<ShortName></ShortName>
<BinBits>0</BinBits>
</Genotype>
<Genotype>
<Name>Mutant</Name>
<ShortName></ShortName>
<BinBits>2</BinBits>
</Genotype>
</Genotypes>
</DefaultScatterGenotypes>
<DefaultMeltGenotypes>
<Genotypes></Genotypes>
</DefaultMeltGenotypes>
<Locked>False</Locked>
<AllowExclusionEnabling>True</AllowExclusionEnabling>
<PluginProgID></PluginProgID>
<PluginData></PluginData>
<Analyses></Analyses>
</Experiment>
